import Head from "next/head";
import Link from "next/link";
import MonacoEditor from "~/components/MonacoEditor";
import Flow from "~/components/react-flow/ReactFlowCom";

export default function Home() {
  return (
    <>
      <Head>
        <title>OpenTelemetry Collector Web</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <MonacoEditor />
        
        {/* <Link href="/react-flow">go to the flow</Link> */}
      </main>
    </>
  );
}
