name: Check for new OpenTelemetry collector releases to support
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch: {}

jobs:
  check-community-releases:
    name: Check new OpenTelemetry Collector community releases
    strategy:
      fail-fast: false
      matrix:
        github_projects: ['open-telemetry/opentelemetry-collector-releases']
        artifact_prefix: ['otelcol', 'otelcol-contrib']
        artifact_suffix: ['linux_amd64.rpm']
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.list-releases.outputs.releases }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        env:
          NODE_MAJOR: 20
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg      
          echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
          sudo apt-get update
          sudo apt-get install nodejs -y
      - name: Build dependency checker application
        run: |
          (cd .github/workflows/scripts/list-releases && npm install && npm run build)
      - name: List matching releases
        id: list-releases
        env:
          DISTRO_NAME: ${{ matrix.artifact_prefix }}
          GH_REPOSITORY: ${{ matrix.github_projects }}
          GH_ASSET_PREFIX: ${{ matrix.artifact_prefix }}_
          GH_ASSET_SUFFIX: _${{ matrix.artifact_suffix }}
        run: |
          (cd .github/workflows/scripts/list-releases && npm run start) > releases.json
          cat releases.json
      - name: Upload releases.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: releases-${{ matrix.artifact_prefix }}.json
          path: releases.json

  open-pr:
    name: Open PR
    needs: check-community-releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          path: releases/
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Merge release data
        run: |
          jq -rs 'reduce .[] as $item ({}; . * $item)' validation-src/src/assets/supported-distributions.json releases/*.json > validation-src/src/assets/supported-distributions-updated.json
      - name: Upload updated releases.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: supported-distributions.json
          path: validation-src/src/assets/supported-distributions-updated.json
      # - name: Prepare PR
      #   run: |
      #     mv validation-src/src/assets/supported-distributions-updated.json validation-src/src/assets/supported-distributions.json
      #       - name: Create Pull Request
      # - name: Create PR
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: "${{ secrets.GITHUB_TOKEN }}"
      #     title: Update supported distribution versions
      #     branch: ${{steps.branch_name.outputs.branch_name}}
      #     commit-message: Update supported distribution versions
      #     body: ''
      #     base: main
      #     labels: version-testing, automerge
      #     reviewers: mmanciop,bripkens
